# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Local Inverse Simpson Index (LISI)
#'
#' @param D Distance matrix of K nearest neighbors.
#' @param knn_idx Adjacency matrix of K nearest neighbors.
#' @param batch_labels A categorical variable.
#' @param n_batches The number of categories in the categorical variable.
#' @param perplexity The effective number of neighbors around each cell.
#' @param tol Stop when the score converges to this tolerance.
#' @export
compute_simpson_index <- function(D, knn_idx, batch_labels, n_batches, perplexity = 15, tol = 1e-5) {
    .Call('_scPOP_compute_simpson_index', PACKAGE = 'scPOP', D, knn_idx, batch_labels, n_batches, perplexity, tol)
}

#' Count pairs in vectors
#' @param classi1 first vector to compare
#' @param classi2 second vector to compare
#' @param order proper order of vectors
#' @export
countPairs <- function(classi1, classi2, order) {
    .Call('_scPOP_countPairs', PACKAGE = 'scPOP', classi1, classi2, order)
}

#' get rank of vector
#' @param classi vector to rank
#' @export
getRank <- function(classi) {
    .Call('_scPOP_getRank', PACKAGE = 'scPOP', classi)
}

